### ISSUE TITLE
Feature request: Re-analysing a user-specified subset of data

### ISSUE THREAD

**Issue by PeteHaitch** [kanaverse/kana#112]
It would be great if it were possible to select a subset of cells and re-analyse that subset.
E.g., In a dataset of PBMCs, select all 'B cells' (based on the cluster annotations) and re-analyse to look for subclusters within the B cell population.
Is this something planned for future release or that would be feasible to implement?

**Comment by jkanche** [comment]
that's a great idea. we could enable this by making the cluster names clickable and automatically open a new session with this subset. 

What really happens in the background is the app would subset the cells in that cluster, create a new h5ad and store this in the browser. the new session chooses this dataset for analysis. Tracking the provenance of datasets and subsets is left to the user.

**Comment by PeteHaitch** [comment]
Awesome!
Thank you for considering the suggestion and for making such a great app.

**Comment by LTLA** [comment]
It took a while, but we accidentally added this feature as a combination of other features.

The workflow goes like this:

- Do an analysis on the full dataset.
- Save the results as ZIP file.
- Start a new analysis (possibly on a different tab, if you want to look at both at once), loading the aforementioned ZIP file.
- Click on "subsetting by annotation" and choose what you want to subset by.

This allows you to subset by cluster numbers or custom selections (choose 1 for cells inside the selection). And of course, you can pick any of your existing annotations if you want.

Admittedly, this isn't the streamlined experience I was thinking about in #120, but I would argue that this approach is more transparent and reproducible, as the user is obliged to save a copy of the original analysis. If we just added an "analyze subset" button directly, **kana** would have to keep track of the provenance of the subsets - tracking how they were generated in the configuration, invalidating them if the parent analysis changes, saving them in the results, etc...

**Comment by PeteHaitch** [comment]
Thanks!

If someone has a processed dataset in another format (e.g., `.rds` containing a _SingleCellExperiment_ object) can they go directly to loading it and "subsetting by annotation"?

**Comment by PeteHaitch** [comment]
Fantastic, thank you!
