### ISSUE TITLE
Pile of issues for bakana v3

### ISSUE THREAD

**Issue by LTLA** [kanaverse/kana#157]
# Overview

UI updates for **bakana** version 2.0.0 (currently in alpha, see [latest version on NPM](https://www.npmjs.com/package/bakana)).

# Major

## Inputs

Input preflights have been completely overhauled to add more information. For example, the SE preflight now provides a list of experiments and assays, in addition to the row/column data. Even the MatrixMarket preflight now provides a list of feature types. This enables users to, e.g., pick which feature type corresponds to RNA, select the assay containing the count matrix, and so on. No more guesswork.

This is particularly important for choosing the "primary feature identifier", which will be used to define the intersection of common features when combining multiple datasets. Again, no need to guess the species or Ensembl/symbol nature of the identifiers, as we'll ask the user to confirm it all. (Of course, the initial defaults can be guessed, but at least then it's not so essential that we get it 100% correct.)

This requires a UI change to support dataset type-specific parameters. For example, SEs and H5ADs can have multiple assays and more rowData, whereas the 10X HDF5 and MatrixMarket formats do not. SEs also have multiple alternative experiments that can be used to define different modalities. Once parameters are chosen, they should be passed to the worker to configure the `InputsState` before `runAnalysis`.

## Quality control

Quality control can no longer be skipped for any modality. That is to say, the QC metrics and thresholds are always produced for each (available) modality; but it is now the responsibility of the `cell_filtering` step to decide whether or not the filters for each modality are applied to the filtered matrix. This change means that it is now always possible for the UI to color the plot by QC metrics, and to produce other diagnostics that are arguably important even if the user doesn't want to use them for filtering.

I suppose the "skip" arguments should be renamed to "use for filtering".

## Summaries

The `summary()` method no longer exists. Instead, we added many getters, and it is now the application's responsibility to format this information into a desirable message. This provides more flexibility for message formatting as we no longer have to update **bakana** whenever we decide to change the format a little. 

So, the `startFun` and `finishFun` arguments to `runAnalysis` now accept the name of the step. This can be used to extract the appropriate `State` object, invoke the getters, and pull out all results required by the UI. Be mindful that the getters don't make copies, so we have to `slice()` any buffers that might get transferred.

Recovering the correct formatting probably requires migrating a few functions from **bakana** v1.2, e.g., `formatMarkerResults`, `splitQCMetricsByBlock`, etc.

## Added CRISPR support

Added support for CRISPR quality control (based on the count of the most abundant guide), normalization (by library size) and PCA (just in case anyone wants to cluster by guide). It is also theoretically possible to do a combined embedding involving information from guides and other modalities, though this seems less useful to me. Anyway, the guide information also shows up in the marker tables, so that's another choice.

Many of the datasets also have a choice for the CRISPR feature type, e.g., `TenxMatrixMarketDataset` allows you to set `featureTypeCrisprName`, which defaults to `"CRISPR Guide Capture"`.

# Minor

- [x] `sample_factor` renamed to `block_factor` for choosing the blocking factor, to avoid confusion between samples and datasets when a dataset can contain multiple samples.
- [x] `resolution` renamed to `multilevel_resolution` for multi-level SNN clustering, to disambiguate between that and the corresponding resolution parameter for Leiden clustering. 
- [x] add choice of SNN graph clustering algorithms (Leiden, Walktrap, Multilevel) + their params. This includes `leiden_resolution` and `walktrap_steps`, which are only relevant for their respective algorithms.
- [x] add "compute AUC?" and "Log-FC threshold" options for marker detection.
- [x] weights in `combine_embeddings` are now explicit per modality, e.g., `rna_weight`, `crispr_weight`. Removed support for the `null` special case, given that `crispr_weight = 0` by default.
- [x] `quality_control`, `pca` and `normalization` all have an `rna_*` prefix now, to better disambiguate those steps for RNA from the corresponding steps of the other modalities.
- [x] `fetchFilteredAnnotation` no longer exists. Worker should instead call `InputsState#fetchCellAnnotations()`, pick the column of interest, and then run `CellFilteringState#applyFilter()` on the resulting column.
- [x] `fetchNormalizedExpression` no longer exists. Worker should instead call `fetchNormalizedMatrix()` for the relevant modality, and then call `.row()` with the row index of interest to get the row of expression values.
- [x] `parseKanaFile` now returns an object, and the `load` value must be passed as `loadFun` to `loadAnalysis`.
- [x] _bakana-remotes_ now have `setDownloadFun` as a static method inside `ExperimentHubDataset`, so as to distinguish it from other download functions that are specific to other remote backends.

**Comment by jkanche** [comment]
I am rewriting the entire app, haven't made much progress but focusing more on the inputs section

**Comment by LTLA** [comment]
need a hackathon at ur plaece

will bring the toilet paper

**Comment by jkanche** [comment]
changes happening in #158
