### ISSUE TITLE
Black screen when clicking on selection. 

### ISSUE THREAD

**Issue by Chengwei94** [kanaverse/kana#191]
![image](https://user-images.githubusercontent.com/61018420/233288185-41a851b2-afb2-41fc-b675-d3680244461a.png)

Really awesome tool there. However, when I click selection1 this black screen bug appears.  Also, I think it would be nicer if theres a loading/computation-bar after I click analyze and the ability to save the file as rds/h5ad for further processing on scanpy/seurat

**Comment by jkanche** [comment]
Thanks for reporting the issue and the feedback. 

Can you let me know what browser and OS you are using? 

There is a spinner that shows up in the left bar when the analysis is running. We'll think of a better place for this. 
![image](https://user-images.githubusercontent.com/399324/233391296-c51d87a2-e084-4928-9887-fcb220c5db8c.png)

When you download the analysis results as ZIP, we create a language agnostic representations of the results and the dataset. This would allow you to load the analysis in R or Python. Check out the [alabaster](https://github.com/ArtifactDB/alabaster.sce) packages from ArtifactDB to load the `SingleCellExperiment`. A Python version would come later.

**Comment by Chengwei94** [comment]
I am using Windows and Google Chrome, but my colleague who is using Mac have met the same problem. I cant reproduce the issue now though, so Ill feedback again after I can reproduce it.

Regarding the spinner, I think it doesnt match the output. My spinner only spins for 0.1s , but the TSNE is only updated after 5s. I think the spinner as the process bar is pretty neat idea though and looks fine when it is working

**Comment by jkanche** [comment]
Hey @Chengwei94, I just push a couple of commits that would hopefully fix this issue (#196). I notice this on annotation with gradients toggled. Hope that fixes it but let me know if you continue to see the dark screen.
