### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by kokitsuyuzaki** [kanaverse/kana#200]
Thanks for great tool!
In analyzing my own data, however, I could't load the data with the web app version, and I tried to start kana on my local machine, but npm and yarn settings did not work.

What about publishing a Docker container on DockerHub or GPCR that contains kana and the dependent tools, and easily start kana on the user's local machine with the docker command?

**Comment by jkanche** [comment]
thank you, we could add a docker file for making it easier for local development. since kana is a pure front end app, you can switch to the gh-pages branch and use `serve` or any other tool that can serve static html.  

now to the actual question, can you give us the error you are running into when loading your dataset? It might help us narrow the issue. webassembly currently has a 4GB memory limit, so if you are loading large datasets, it might be running out of memory.

**Comment by kokitsuyuzaki** [comment]
Thanks, I'm looking forward to the Docker image.
I'll attach the error message belows.
As you said, this might be because of the data size; the matrix size is 20359 x 82552.

```
14:06:39: (experimenthub) store initialized
14:06:39: (downloadsdb) store initialized
14:06:39: (kanadb) store initialized
14:06:39: analysis state created
14:06:39: bakana initialized
14:07:32: preflight_input finished
14:07:32: RuntimeError: Aborted(). Build with -s ASSERTIONS=1 for more info.
```

**Comment by jkanche** [comment]
that doesn't seem that big, we benchmarked kana on datasets with #cells ~170K. Do you see any errors in the console/devtools? 

also **if** this is a **public** dataset, can you give us the link so we can also debug this?

**Comment by kokitsuyuzaki** [comment]
Sorry, this data is not public for now.
The file size is 1.96 GB.
I firstly analyzed the data by `Seurat`,
converted it to `SingleCellExperiment` object by `Seurat::as.SingleCellExperiment`,
saved it by `saveRDS`,
and loaded the RDS file in "Start a New Analysis" page.

Does kana use species-specific information?
Our data is about sea urchin, which is not so major species.

I firstly thought that the error is caused because the matrix is dense but it seems that the data matrix is properly converted to a sparse matrix.

```
class: SingleCellExperiment
dim: 20359 82552
metadata(0):
assays(2): counts logcounts
rownames(20359): Hp-Dcamkl2 Hp-Hypp-0001 ... Hp-Hypp-7387 Hp-Nadsyn1-1
rowData names(0):
colnames(82552): AAACCCAAGGAGGTTC-1_1 AAACCCACAAGCGCTC-1_1 ...
  TTTGTTGTCGGCTGTG-1_10 TTTGTTGTCTGCGTCT-1_10
colData names(9): orig.ident nCount_RNA ... sample ident
> sce
class: SingleCellExperiment
dim: 20359 82552
metadata(0):
assays(2): counts logcounts
rownames(20359): Hp-Dcamkl2 Hp-Hypp-0001 ... Hp-Hypp-7387 Hp-Nadsyn1-1
rowData names(0):
colnames(82552): AAACCCAAGGAGGTTC-1_1 AAACCCACAAGCGCTC-1_1 ...
  TTTGTTGTCGGCTGTG-1_10 TTTGTTGTCTGCGTCT-1_10
colData names(9): orig.ident nCount_RNA ... sample ident

> str(assays(sce))
Formal class 'SimpleList' [package "S4Vectors"] with 4 slots
  ..@ listData       :List of 2
  .. ..$ counts   :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. ..@ i       : int [1:83447717] 38 55 134 149 159 162 178 185 269 344 ...
  .. .. .. ..@ p       : int [1:82553] 0 550 2442 3135 4001 5606 7643 9605 11233 12681 ...
  .. .. .. ..@ Dim     : int [1:2] 20359 82552
  .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. ..$ : chr [1:20359] "Hp-Dcamkl2" "Hp-Hypp-0001" "Hp-Dnajhc9" "Hp-Slc10a2-6" ...
  .. .. .. .. ..$ : chr [1:82552] "AAACCCAAGGAGGTTC-1_1" "AAACCCACAAGCGCTC-1_1" "AAACCCACACAGCATT-1_1" "AAACCCACATGGGTTT-1_1" ...
  .. .. .. ..@ x       : num [1:83447717] 2 2 2 2 2 110 2 1 2 1 ...
  .. .. .. ..@ factors : list()
  .. ..$ logcounts:Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. ..@ i       : int [1:83447717] 38 55 134 149 159 162 178 185 269 344 ...
  .. .. .. ..@ p       : int [1:82553] 0 550 2442 3135 4001 5606 7643 9605 11233 12681 ...
  .. .. .. ..@ Dim     : int [1:2] 20359 82552
  .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. ..$ : chr [1:20359] "Hp-Dcamkl2" "Hp-Hypp-0001" "Hp-Dnajhc9" "Hp-Slc10a2-6" ...
  .. .. .. .. ..$ : chr [1:82552] "AAACCCAAGGAGGTTC-1_1" "AAACCCACAAGCGCTC-1_1" "AAACCCACACAGCATT-1_1" "AAACCCACATGGGTTT-1_1" ...
  .. .. .. ..@ x       : num [1:83447717] 1.1 1.1 1.1 1.1 1.1 ...
  .. .. .. ..@ factors : list()
  ..@ elementType    : chr "ANY"
  ..@ elementMetadata: NULL
  ..@ metadata       : list()
  ```

**Comment by LTLA** [comment]
Almost 2GB! For 80K cells? That's very unusual. I could store half a million cells in 2GB with the HDF5-based formats. Even the Bachter T cell data (`scRNAseq::BacherTCellData()`) is just a bit over 300 MB after `saveRDS()`, and that's with 143 million non-zero elements. I would suggest slimming down the SCE manually, e.g., there's no need for the log-counts, as we compute that in the app, and there's probably no need for any reduced dims if you're not using explore-only mode.

**Comment by kokitsuyuzaki** [comment]
Thanks for the info.
It looks like the object sizes of sce@int_colData and sce@assays are quite large.

```
> object.size(sce@int_elementMetadata)
3520 bytes
> object.size(sce@int_colData)
4154758232 bytes
> object.size(sce@int_metadata)
896 bytes
> object.size(sce@rowRanges)
1566256 bytes
> object.size(sce@colData)
11568528 bytes
> object.size(sce@assays)
2020882736 bytes
> object.size(sce@NAMES)
0 bytes
> object.size(sce@elementMetadata)
1720 bytes
> object.size(sce@metadata)
48 bytes
```

I ran the following code and was able to load it into kana.

```
sce@int_colData@listData$reducedDims <- NULL
sce@int_colData@listData$altExps <- NULL
logcounts(sce) <- NULL
```

By the way, if it is possible, I would like to use the UMAP coordinates already calculated by Seurat.
Do you have such an option?

**Comment by jkanche** [comment]
you can load the RDS file in explore mode to look at pre computed embeddings in kana

**Comment by LTLA** [comment]
A few closing remarks:

- Unrelated, but you can (and should) modify your object using the getters (`altExp()` and `reducedDim()`) rather than directly accessing slots via `@`. The latter is not robust to internal changes in the class definition.
- As for the title of this issue: Docker's not going to help here. Application performance (and the debugging experience) is not going to be any better inside a container compared to just running it on your browser.

**Comment by kokitsuyuzaki** [comment]
Thanks, @LTLA

@jkanche Where is the explore mode available?
I found such a source-code is here but don't know how this component is used on web-browser...
https://github.com/kanaverse/kana/blob/master/src/components/ExploreMode/index.js

**Comment by jkanche** [comment]
the second banner (green) on the homescreen - `I want to explore existing analysis results`

<img width="921" alt="image" src="https://user-images.githubusercontent.com/399324/234146724-ab854508-61f6-4a14-aa00-76f4ac347723.png">

**Comment by kokitsuyuzaki** [comment]
I could use the result of `Seurat` !
Thanks, @jkanche !!!
