### ISSUE TITLE
Region related gene list

### ISSUE THREAD

**Issue by kokitsuyuzaki** [kanaverse/kana#208]
Sorry for bothering you again.

In previous versions of `kana` in explore mode, I could select a region on the left UMAP panel, the selected region was automatically named such as "Selection 1", and then I could view the genes associated with the region on the center Markers panel.

However, in v3.0.9 this functionality seems to be no longer available.
Perhaps this is related around the removal of this `setAnnotationCols` function.
https://github.com/kanaverse/kana/commit/36c5cb6498734177d756dcbe50b96ee11af3853f

Do you have any plan to bring it back in the future?
That was my favorite functionality and I would be happy to have it available again.

**Comment by jkanche** [comment]
oops, thats a bug, I'll fix this soon

**Comment by jkanche** [comment]
Thanks @kokitsuyuzaki for reporting this issue. Let me know if you see any more issues!
