### ISSUE TITLE
TypeError: e is not an Object. (evaluating '"_bioconductor_SLICE"in e')

### ISSUE THREAD

**Issue by suragnair** [kanaverse/kana#228]
Hi thanks for the cool tool. I'm getting `TypeError: e is not an Object. (evaluating '"_bioconductor_SLICE"in e')` when I try uploading the following h5ad from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE176206: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE176nnn/GSE176206/suppl/GSE176206%5Fmyo%5Fmsx1%2Eh5ad%2Egz

I gunzip-ed the file prior to loading. Thanks and let me know if you need more information.

**Comment by jkanche** [comment]
I think i know whats happening, for now until we push a fix if you remove the `_scvi_*` cell annotation columns (in the `obs` slot) from the h5ad, it would work.

**Comment by suragnair** [comment]
great it works now, thanks! However the UMAP doesn't load in Safari 16.5.1. I am able to get it to work in Edge however.

How long do you expect the fix to be live?

**Comment by jkanche** [comment]
also Kana works on firefox, chrome and its variants. 

Safari does not support the latest web technologies we need to perform the analysis in the browser.
