### ISSUE TITLE
Subsetting by annotation is broken

### ISSUE THREAD

**Issue by PeteHaitch** [kanaverse/kana#241]
Steps to reproduce:

1. I want to analyze a new dataset
2. ExperimentHub > zeisel-brain > Add dataset
3. Subsetting by annotation > tissue

Result is a blank screen and seemingly the app quits.

This was under Chrome Version 116.0.5845.110 (Official Build) (arm64)

**Comment by LTLA** [comment]
whoops. Looks like we missed a spot in ceb174f7891cde627aac11cca19877558d2e3e57.

**Comment by PeteHaitch** [comment]
Thanks for the quick fix.
