### ISSUE TITLE
Possible to visualize pre-done clustering?

### ISSUE THREAD

**Issue by ohmstead** [kanaverse/kana#251]
Hi there,

kana looks like a beautiful tool for visualizing single-cell data. I'm wondering, is it possible to upload an .h5ad file that already has clusters annotated?

I've already performed my filtering, normalization, feature selection, dimension reduction, and clustering on my own. I would just like to explore my data interactively with kana.

If there is a better interaction/exploration tool out there, I would appreciate recommendations as well!

**Comment by jkanche** [comment]
@ohmstead, Kana does support an explore-mode, to explore pre-analyzed results. This [wiki](https://github.com/kanaverse/kana/wiki/How-to-explore-pre%E2%80%90analyzed-single%E2%80%90cell-datasets) article should help you get started.

Let us know if you have any issues.

**Comment by ohmstead** [comment]
@jkanche, I'm having trouble viewing my data in explore mode. I'm able to upload my AnnData .h5ad object, but I get the same error consistently: **TypeError: Cannot convert undefined or null to object**.

I don't know what "Feature type column name" means or what I'm supposed to select here. I only have RNA data in my adata object.

Here is the full log for a run:

> 10:10:19 AM: (downloadsdb) store initialized
> 10:10:19 AM: analysis state created
> 10:10:19 AM: bakana initialized
> 10:10:25 AM: preflight_input finished
> 10:11:26 AM: --- Analyis started---
> 10:11:26 AM: TypeError: Cannot convert undefined or null to object

**Comment by jkanche** [comment]
@ohmstead, is it possible to share the h5ad object with us? or you can also point us to the file, If its a public dataset. 

otherwise if you have `h5dump` installed, can you post the output on this file here?

**Comment by ohmstead** [comment]
@jkanche, I would be happy to. What is the best way privately share a link?

**Comment by ohmstead** [comment]
I just installed h5dump, but I'm not sure how I would interface that with the webapp. It's not giving me an h5 log file to open, to my knowledge.

Can you walk me through?

**Comment by jkanche** [comment]
alright, can you share the file on google drive? (jayaram.kancherla@gmail.com)

**Comment by jkanche** [comment]
@ohmstead Thank you for sharing the file to identify the bug. In a few minutes the app (v3.0.20) will automatically update to the new version.

Thanks for reporting the issue and reach out if you run into more issues.

**Comment by jkanche** [comment]
Just tested on the deployed version and it works!

**Comment by ohmstead** [comment]
Yes it works for me as well! Thank you.
