### ISSUE TITLE
missing annotations

### ISSUE THREAD

**Issue by ohmstead** [kanaverse/kana#253]
I successfully loaded a pre-analyzed .h5ad file into the browser. Basic functionality looks great. Two questions:

1. The "supplied" `annotations` dropdown list is missing several of the metadata columns I have in my `adata.obs` object. Is there a way for me to structure my AnnData object so I can have them included?
![Screenshot of all annotations. Some columns from adata.obs are not included](https://github.com/kanaverse/kana/assets/20440639/97516cc5-24dc-4ff5-91c1-e2d8061c0ccb)
2. The gene information is sorted by ensemble gene ID and not gene symbols. My gene symbols are stored in `adata.var.index`. How can I access these instead of ensembl IDs?
![Screenshot 2024-01-17 at 3 22 39 PM](https://github.com/kanaverse/kana/assets/20440639/5bc5a06b-aec9-48fb-a120-f9b48f9c576d)

As a general note, I think it would be helpful to have documentation explaining where inside the standard structure of AnnData objects certain metadata is being pulled from by kana!

**Comment by jkanche** [comment]
> The "supplied" annotations dropdown list is missing several of the metadata columns I have in my adata.obs object. Is there a way for me to structure my AnnData object so I can have them included?

@ohmstead, The reason they are missing from the dropdown is these annotations have way too many categories (> 50). Any visualization on these columns is not super helpful. But i can see how this is confusing to the user.

> The gene information is sorted by ensemble gene ID and not gene symbols. My gene symbols are stored in adata.var.index. How can I access these instead of ensembl IDs?

The table ranks marker genes, they are not sorted alphabetically. (i) icon provide more information for each of these panels.
![image](https://github.com/kanaverse/kana/assets/399324/4048505e-8797-436d-8fd7-3938c6b416e5)

We let the user choose what to display (defaults to ensembl ids, if the dataset contains one) in this table. click on `gene_id` label should show a dropdown of all available feature columns:
![image](https://github.com/kanaverse/kana/assets/399324/697b1178-3b7c-407b-a45f-4c1233fe8664)

AnnData's index for `var` maps to "rowNames" in the R/Bioconductor world
![image](https://github.com/kanaverse/kana/assets/399324/77126c4d-24d9-4d72-9d50-9c16a37b0bf3)

**Comment by ohmstead** [comment]
@jkanche Thank you for showing me where to find gene symbols! I see them now.

I respectfully disagree that columns with many categories aren't helpful for visualizing. For example, in my case I have 63 cell types in my sample, but only about a dozen large clusters. It would be very nice to visualize all my cell types.

**Comment by jkanche** [comment]
@ohmstead: Just pushed a version that does not truncate the annotation list anymore. Let me know if that works for you! Thank you for the feedback 👍🏽

**Comment by ohmstead** [comment]
Your responsiveness is amazing! Thanks so much
